apiVersion: grafana.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: grafana-cloud-instance-provider
spec:
  credentials:
    secretRef:
      key: credentials
      name: grafana-creds
      namespace: crossplane-system
    source: Secret